
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow {
	private global::Gtk.EventBox EventBox1;

	private global::Gtk.Image Map;

	protected virtual void Build() {
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.EventBox1 = new global::Gtk.EventBox();
		this.EventBox1.Name = "EventBox1";
		// Container child EventBox1.Gtk.Container+ContainerChild
		this.Map = new global::Gtk.Image();
		this.Map.Name = "Map";
		this.Map.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Moi.Selection_012.png");
		this.EventBox1.Add(this.Map);
		this.Add(this.EventBox1);
		if ((this.Child != null)) {
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1754;
		this.DefaultHeight = 954;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.EventBox1.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.MapClick);
		this.Map.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.MapClick);
	}
}
