
// This file has been generated by the GUI designer. Do not modify.
namespace Moi
{
	public partial class EdgeWindow
	{
		private global::Gtk.VBox vbox4;

		private global::Gtk.VBox vbox5;

		private global::Gtk.VPaned vpaned1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.HPaned hpaned3;

		private global::Gtk.Label StartLabel;

		private global::Gtk.Entry IniEntry;

		private global::Gtk.HPaned hpaned4;

		private global::Gtk.VPaned vpaned2;

		private global::Gtk.HBox hbox5;

		private global::Gtk.HPaned hpaned5;

		private global::Gtk.Label EndLabel;

		private global::Gtk.Entry FinEntry;

		private global::Gtk.HPaned hpaned6;

		private global::Gtk.VPaned vpaned3;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox6;

		private global::Gtk.HPaned hpaned7;

		private global::Gtk.Label CostLabel;

		private global::Gtk.Entry CostEntry;

		private global::Gtk.HPaned hpaned8;

		private global::Gtk.VPaned vpaned4;

		private global::Gtk.HBox hbox7;

		private global::Gtk.HPaned hpaned9;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Button CancelButton;

		private global::Gtk.HPaned hpaned11;

		private global::Gtk.Button AcceptButton;

		private global::Gtk.HPaned hpaned10;

		private global::Gtk.VPaned vpaned5;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Moi.EdgeWindow
			this.Name = "Moi.EdgeWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("EdgeWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Moi.EdgeWindow.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vpaned1 = new global::Gtk.VPaned();
			this.vpaned1.CanFocus = true;
			this.vpaned1.Name = "vpaned1";
			this.vpaned1.Position = 10;
			this.vbox5.Add(this.vpaned1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vpaned1]));
			w1.Position = 0;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hpaned3 = new global::Gtk.HPaned();
			this.hpaned3.CanFocus = true;
			this.hpaned3.Name = "hpaned3";
			this.hpaned3.Position = 10;
			this.hbox4.Add(this.hpaned3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hpaned3]));
			w2.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.StartLabel = new global::Gtk.Label();
			this.StartLabel.Name = "StartLabel";
			this.StartLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Start");
			this.hbox4.Add(this.StartLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.StartLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.IniEntry = new global::Gtk.Entry();
			this.IniEntry.WidthRequest = 100;
			this.IniEntry.CanFocus = true;
			this.IniEntry.Name = "IniEntry";
			this.IniEntry.IsEditable = true;
			this.IniEntry.InvisibleChar = '●';
			this.hbox4.Add(this.IniEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.IniEntry]));
			w4.Position = 2;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hpaned4 = new global::Gtk.HPaned();
			this.hpaned4.CanFocus = true;
			this.hpaned4.Name = "hpaned4";
			this.hpaned4.Position = 10;
			this.hbox4.Add(this.hpaned4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hpaned4]));
			w5.Position = 3;
			this.vbox5.Add(this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox4]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vpaned2 = new global::Gtk.VPaned();
			this.vpaned2.CanFocus = true;
			this.vpaned2.Name = "vpaned2";
			this.vpaned2.Position = 10;
			this.vbox5.Add(this.vpaned2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vpaned2]));
			w7.Position = 2;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hpaned5 = new global::Gtk.HPaned();
			this.hpaned5.CanFocus = true;
			this.hpaned5.Name = "hpaned5";
			this.hpaned5.Position = 10;
			this.hbox5.Add(this.hpaned5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hpaned5]));
			w8.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.EndLabel = new global::Gtk.Label();
			this.EndLabel.Name = "EndLabel";
			this.EndLabel.LabelProp = global::Mono.Unix.Catalog.GetString("End");
			this.hbox5.Add(this.EndLabel);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.EndLabel]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.FinEntry = new global::Gtk.Entry();
			this.FinEntry.WidthRequest = 100;
			this.FinEntry.CanFocus = true;
			this.FinEntry.Name = "FinEntry";
			this.FinEntry.IsEditable = true;
			this.FinEntry.InvisibleChar = '●';
			this.hbox5.Add(this.FinEntry);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.FinEntry]));
			w10.Position = 2;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hpaned6 = new global::Gtk.HPaned();
			this.hpaned6.CanFocus = true;
			this.hpaned6.Name = "hpaned6";
			this.hpaned6.Position = 10;
			this.hbox5.Add(this.hpaned6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hpaned6]));
			w11.Position = 3;
			this.vbox5.Add(this.hbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox5]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vpaned3 = new global::Gtk.VPaned();
			this.vpaned3.CanFocus = true;
			this.vpaned3.Name = "vpaned3";
			this.vpaned3.Position = 10;
			this.vbox5.Add(this.vpaned3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vpaned3]));
			w13.Position = 4;
			this.vbox4.Add(this.vbox5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox5]));
			w14.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hpaned7 = new global::Gtk.HPaned();
			this.hpaned7.CanFocus = true;
			this.hpaned7.Name = "hpaned7";
			this.hpaned7.Position = 10;
			this.hbox6.Add(this.hpaned7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hpaned7]));
			w15.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.CostLabel = new global::Gtk.Label();
			this.CostLabel.Name = "CostLabel";
			this.CostLabel.LabelProp = global::Mono.Unix.Catalog.GetString("Cost");
			this.hbox6.Add(this.CostLabel);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.CostLabel]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.CostEntry = new global::Gtk.Entry();
			this.CostEntry.WidthRequest = 100;
			this.CostEntry.CanFocus = true;
			this.CostEntry.Name = "CostEntry";
			this.CostEntry.IsEditable = true;
			this.CostEntry.InvisibleChar = '●';
			this.hbox6.Add(this.CostEntry);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.CostEntry]));
			w17.Position = 2;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hpaned8 = new global::Gtk.HPaned();
			this.hpaned8.CanFocus = true;
			this.hpaned8.Name = "hpaned8";
			this.hpaned8.Position = 10;
			this.hbox6.Add(this.hpaned8);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hpaned8]));
			w18.Position = 3;
			this.vbox6.Add(this.hbox6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vpaned4 = new global::Gtk.VPaned();
			this.vpaned4.CanFocus = true;
			this.vpaned4.Name = "vpaned4";
			this.vpaned4.Position = 10;
			this.vbox6.Add(this.vpaned4);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vpaned4]));
			w20.Position = 1;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hpaned9 = new global::Gtk.HPaned();
			this.hpaned9.CanFocus = true;
			this.hpaned9.Name = "hpaned9";
			this.hpaned9.Position = 10;
			this.hbox7.Add(this.hpaned9);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hpaned9]));
			w21.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.CancelButton = new global::Gtk.Button();
			this.CancelButton.WidthRequest = 70;
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = global::Mono.Unix.Catalog.GetString("Cancel");
			this.hbox8.Add(this.CancelButton);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.CancelButton]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hpaned11 = new global::Gtk.HPaned();
			this.hpaned11.CanFocus = true;
			this.hpaned11.Name = "hpaned11";
			this.hpaned11.Position = 10;
			this.hbox8.Add(this.hpaned11);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hpaned11]));
			w23.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.AcceptButton = new global::Gtk.Button();
			this.AcceptButton.WidthRequest = 70;
			this.AcceptButton.CanFocus = true;
			this.AcceptButton.Name = "AcceptButton";
			this.AcceptButton.UseUnderline = true;
			this.AcceptButton.Label = global::Mono.Unix.Catalog.GetString("Accept");
			this.hbox8.Add(this.AcceptButton);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.AcceptButton]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox7.Add(this.hbox8);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox8]));
			w25.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hpaned10 = new global::Gtk.HPaned();
			this.hpaned10.CanFocus = true;
			this.hpaned10.Name = "hpaned10";
			this.hpaned10.Position = 10;
			this.hbox7.Add(this.hpaned10);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hpaned10]));
			w26.Position = 2;
			this.vbox6.Add(this.hbox7);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox7]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.vpaned5 = new global::Gtk.VPaned();
			this.vpaned5.CanFocus = true;
			this.vpaned5.Name = "vpaned5";
			this.vpaned5.Position = 10;
			this.vbox6.Add(this.vpaned5);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.vpaned5]));
			w28.Position = 3;
			this.vbox4.Add(this.vbox6);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox6]));
			w29.Position = 1;
			this.Add(this.vbox4);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 360;
			this.DefaultHeight = 262;
			this.Show();
			this.CancelButton.Clicked += new global::System.EventHandler(this.CancelButtonClicked);
			this.AcceptButton.Clicked += new global::System.EventHandler(this.AcceptButtonClicked);
		}
	}
}
