
// This file has been generated by the GUI designer. Do not modify.
namespace Moi {
	public partial class DjkstraWindow {
		private global::Gtk.VBox vbox7;

		private global::Gtk.VBox vbox8;

		private global::Gtk.VPaned vpaned7;

		private global::Gtk.HBox hbox10;

		private global::Gtk.HPaned hpaned14;

		private global::Gtk.Label StartLabel;

		private global::Gtk.Entry StartEntry;

		private global::Gtk.HPaned hpaned15;

		private global::Gtk.VPaned vpaned8;

		private global::Gtk.HPaned hpaned12;

		private global::Gtk.HBox hbox11;

		private global::Gtk.HPaned hpaned13;

		private global::Gtk.Label FinishLabel;

		private global::Gtk.Entry FinishEntry;

		private global::Gtk.HPaned hpaned16;

		private global::Gtk.VPaned vpaned9;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.HBox hbox9;

		private global::Gtk.VPaned vpaned6;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView DjkstraText;

		private global::Gtk.VBox vbox9;

		private global::Gtk.VPaned vpaned10;

		private global::Gtk.HBox hbox13;

		private global::Gtk.HPaned hpaned17;

		private global::Gtk.Button CalculateButton;

		private global::Gtk.HPaned hpaned18;

		private global::Gtk.VPaned vpaned11;

		private global::Gtk.HBox hbox12;

		private global::Gtk.HPaned hpaned19;

		private global::Gtk.Button CloseButton;

		private global::Gtk.HPaned hpaned20;

		private global::Gtk.VPaned vpaned12;

		protected virtual void Build() {
			global::Stetic.Gui.Initialize(this);
			// Widget Moi.DjkstraWindow
			this.Name = "Moi.DjkstraWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("DjkstraWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Moi.DjkstraWindow.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vpaned7 = new global::Gtk.VPaned();
			this.vpaned7.HeightRequest = 10;
			this.vpaned7.CanFocus = true;
			this.vpaned7.Name = "vpaned7";
			this.vpaned7.Position = 10;
			this.vbox8.Add(this.vpaned7);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vpaned7]));
			w1.Position = 0;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hpaned14 = new global::Gtk.HPaned();
			this.hpaned14.CanFocus = true;
			this.hpaned14.Name = "hpaned14";
			this.hpaned14.Position = 10;
			this.hbox10.Add(this.hpaned14);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.hpaned14]));
			w2.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.StartLabel = new global::Gtk.Label();
			this.StartLabel.Name = "StartLabel";
			this.StartLabel.LabelProp = global::Mono.Unix.Catalog.GetString("StartId");
			this.hbox10.Add(this.StartLabel);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.StartLabel]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.StartEntry = new global::Gtk.Entry();
			this.StartEntry.CanFocus = true;
			this.StartEntry.Name = "StartEntry";
			this.StartEntry.IsEditable = true;
			this.StartEntry.InvisibleChar = '●';
			this.hbox10.Add(this.StartEntry);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.StartEntry]));
			w4.Position = 2;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hpaned15 = new global::Gtk.HPaned();
			this.hpaned15.CanFocus = true;
			this.hpaned15.Name = "hpaned15";
			this.hpaned15.Position = 10;
			this.hbox10.Add(this.hpaned15);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.hpaned15]));
			w5.Position = 3;
			this.vbox8.Add(this.hbox10);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox10]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vpaned8 = new global::Gtk.VPaned();
			this.vpaned8.HeightRequest = 10;
			this.vpaned8.CanFocus = true;
			this.vpaned8.Name = "vpaned8";
			this.vpaned8.Position = 10;
			// Container child vpaned8.Gtk.Paned+PanedChild
			this.hpaned12 = new global::Gtk.HPaned();
			this.hpaned12.CanFocus = true;
			this.hpaned12.Name = "hpaned12";
			this.hpaned12.Position = 10;
			this.vpaned8.Add(this.hpaned12);
			this.vbox8.Add(this.vpaned8);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vpaned8]));
			w8.Position = 2;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hpaned13 = new global::Gtk.HPaned();
			this.hpaned13.CanFocus = true;
			this.hpaned13.Name = "hpaned13";
			this.hpaned13.Position = 10;
			this.hbox11.Add(this.hpaned13);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hpaned13]));
			w9.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.FinishLabel = new global::Gtk.Label();
			this.FinishLabel.Name = "FinishLabel";
			this.FinishLabel.LabelProp = global::Mono.Unix.Catalog.GetString("FinishId");
			this.hbox11.Add(this.FinishLabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.FinishLabel]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.FinishEntry = new global::Gtk.Entry();
			this.FinishEntry.CanFocus = true;
			this.FinishEntry.Name = "FinishEntry";
			this.FinishEntry.IsEditable = true;
			this.FinishEntry.InvisibleChar = '●';
			this.hbox11.Add(this.FinishEntry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.FinishEntry]));
			w11.Position = 2;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hpaned16 = new global::Gtk.HPaned();
			this.hpaned16.CanFocus = true;
			this.hpaned16.Name = "hpaned16";
			this.hpaned16.Position = 10;
			this.hbox11.Add(this.hpaned16);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hpaned16]));
			w12.Position = 3;
			this.vbox8.Add(this.hbox11);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox11]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vpaned9 = new global::Gtk.VPaned();
			this.vpaned9.HeightRequest = 10;
			this.vpaned9.CanFocus = true;
			this.vpaned9.Name = "vpaned9";
			this.vpaned9.Position = 10;
			this.vbox8.Add(this.vpaned9);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vpaned9]));
			w14.Position = 4;
			this.vbox7.Add(this.vbox8);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox8]));
			w15.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator();
			this.hseparator1.Name = "hseparator1";
			this.vbox7.Add(this.hseparator1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hseparator1]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vpaned6 = new global::Gtk.VPaned();
			this.vpaned6.HeightRequest = 100;
			this.vpaned6.CanFocus = true;
			this.vpaned6.Name = "vpaned6";
			this.vpaned6.Position = 10;
			// Container child vpaned6.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.DjkstraText = new global::Gtk.TextView();
			this.DjkstraText.CanFocus = true;
			this.DjkstraText.Name = "DjkstraText";
			this.DjkstraText.Editable = false;
			this.DjkstraText.CursorVisible = false;
			this.DjkstraText.LeftMargin = 5;
			this.GtkScrolledWindow.Add(this.DjkstraText);
			this.vpaned6.Add(this.GtkScrolledWindow);
			this.hbox9.Add(this.vpaned6);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vpaned6]));
			w19.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vpaned10 = new global::Gtk.VPaned();
			this.vpaned10.CanFocus = true;
			this.vpaned10.Name = "vpaned10";
			this.vpaned10.Position = 10;
			this.vbox9.Add(this.vpaned10);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.vpaned10]));
			w20.Position = 0;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.hpaned17 = new global::Gtk.HPaned();
			this.hpaned17.CanFocus = true;
			this.hpaned17.Name = "hpaned17";
			this.hpaned17.Position = 10;
			this.hbox13.Add(this.hpaned17);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.hpaned17]));
			w21.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.CalculateButton = new global::Gtk.Button();
			this.CalculateButton.CanFocus = true;
			this.CalculateButton.Name = "CalculateButton";
			this.CalculateButton.UseUnderline = true;
			this.CalculateButton.Label = global::Mono.Unix.Catalog.GetString("Calculate");
			this.hbox13.Add(this.CalculateButton);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.CalculateButton]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.hpaned18 = new global::Gtk.HPaned();
			this.hpaned18.CanFocus = true;
			this.hpaned18.Name = "hpaned18";
			this.hpaned18.Position = 10;
			this.hbox13.Add(this.hpaned18);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.hpaned18]));
			w23.Position = 2;
			this.vbox9.Add(this.hbox13);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox13]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vpaned11 = new global::Gtk.VPaned();
			this.vpaned11.CanFocus = true;
			this.vpaned11.Name = "vpaned11";
			this.vpaned11.Position = 10;
			this.vbox9.Add(this.vpaned11);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.vpaned11]));
			w25.Position = 2;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hpaned19 = new global::Gtk.HPaned();
			this.hpaned19.CanFocus = true;
			this.hpaned19.Name = "hpaned19";
			this.hpaned19.Position = 10;
			this.hbox12.Add(this.hpaned19);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.hpaned19]));
			w26.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.CloseButton = new global::Gtk.Button();
			this.CloseButton.CanFocus = true;
			this.CloseButton.Name = "CloseButton";
			this.CloseButton.UseUnderline = true;
			this.CloseButton.Label = global::Mono.Unix.Catalog.GetString("Close");
			this.hbox12.Add(this.CloseButton);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.CloseButton]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.hpaned20 = new global::Gtk.HPaned();
			this.hpaned20.CanFocus = true;
			this.hpaned20.Name = "hpaned20";
			this.hpaned20.Position = 10;
			this.hbox12.Add(this.hpaned20);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.hpaned20]));
			w28.Position = 2;
			this.vbox9.Add(this.hbox12);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox12]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vpaned12 = new global::Gtk.VPaned();
			this.vpaned12.CanFocus = true;
			this.vpaned12.Name = "vpaned12";
			this.vpaned12.Position = 10;
			this.vbox9.Add(this.vpaned12);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.vpaned12]));
			w30.Position = 4;
			this.hbox9.Add(this.vbox9);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.vbox9]));
			w31.Position = 1;
			this.vbox7.Add(this.hbox9);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox9]));
			w32.Position = 2;
			this.Add(this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll();
			}
			this.DefaultWidth = 402;
			this.DefaultHeight = 488;
			this.Show();
			this.CalculateButton.Clicked += new global::System.EventHandler(this.CalculateButtonClicked);
			this.CloseButton.Clicked += new global::System.EventHandler(this.CloseButtonClicked);
		}
	}
}
